### ISSUE TITLE
Unable to create posts in development

### ISSUE THREAD

**Issue by danielthall** [embersherpa/ember-cli-ghost-app#1]
I am getting a 403 every time I try to create or edit a post, accompanied by the following error:

ERROR: You do not have permission to add posts. 

Any ideas?

**Comment by taras** [comment]
@danielthall I'm sorry, this was a failed experiment. I should destroy this repo.

**Comment by danielthall** [comment]
Ah, that's a shame. Thanks for the quick response.

**Comment by taras** [comment]
Yeah, this needs to be done differently with a proxy that adds this information. Unless Ghost will eventually provide a proper API (which they surpassingly do not)

**Comment by danielthall** [comment]
That answers my next question, which I was just searching for on google. Back to the drawing board, I guess.

**Comment by taras** [comment]
Added a HUGE WARNING :)
